apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: quay.io/openshift-pipeline/my-app:latest
          imagePullPolicy: Always
          name: my-app
          ports:
            - containerPort: 8080
              protocol: TCP